name: Linting and Unit Tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install .[test]
      - name: Enforce PEP 8 style
        run: |
          export PYTHONPATH=`pwd`
          find src tests utils -type f -name "*.py" | while read file
          do
            echo "*** Linting $file ***"
            pylint --rcfile=.pylintrc "$file"
          done

  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      ACCOUNTNAME: ${{ secrets.ACCOUNTNAME }}
      ACCOUNTKEY: ${{ secrets.ACCOUNTKEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install .[test]

      - name: Run unit tests
        run: |
          export PYTHONPATH=`pwd`
          pytest --cov=src --cov-report=xml
